# Generated by Django 2.2.15 on 2020-11-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('client', models.CharField(max_length=64)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
