# Generated by Django 2.2.15 on 2020-11-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(choices=[('round', '圆钢'), ('square', '方钢')], default='round', max_length=12)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
