# Generated by Django 2.2.15 on 2020-11-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('inventory', '0002_inventory_stockinorder_stockinproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutSquareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=32)),
                ('diameter', models.FloatField()),
                ('length', models.FloatField()),
                ('quantity', models.FloatField()),
                ('goods_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('weight', models.FloatField()),
                ('caculate_weight', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('other_fee', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_product_set', to='basic.Product')),
                ('stock_out_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_product_set', to='inventory.StockOutOrder')),
            ],
        ),
    ]
